name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      PolygonApiKey: ${{ secrets.POLYGON_API_KEY }}

    steps:          
      - uses: actions/checkout@v2

      - name: Install SonarQube Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarQube Scanner
        run: dotnet sonarscanner begin /key:"Polygon.Net" /d:sonar.host.url="${{secrets.SONARQUBE_HOST}}" /d:sonar.login="${{secrets.SONARQUBE_TOKEN}}" /d:sonar.scm.disabled=false /d:sonar.scm.provider=git /d:sonar.links.scm="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" /d:sonar.cs.opencover.reportsPaths='**/coverage.opencover.xml'

      - name: Restore Dependencies
        run: dotnet restore Polygon.Net.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute="Obsolete"

      - name: End SonarQube Scanner
        run: dotnet sonarscanner end /d:sonar.login="${{secrets.SONARQUBE_TOKEN}}"